### ISSUE TITLE
Why not charcoal v2?

### ISSUE THREAD

**Issue by ruckustboom** [olup/notable#13]
For the pencil, notable uses `NeoCharcoalPen`
https://github.com/olup/notable/blob/main/app/src/main/java/com/olup/notable/utils/draw.kt#L74

Is there a reason this isn't `NeoCharcoalPenV2`? I'm not sure what the difference is, so I don't understand if V2 means improved or just different.

**Comment by olup** [comment]
It's agood point and I am not sure. When I implemented it in the old SDK V2 wasn't an option. Clearly the thing is the same than what is drawn by the sdk so, I guess i'll keep it that way :-)
